import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

type SpacerProps = {
  orientation: 'vertical' | 'horizontal';
  size: number;
}

const Spacer: React.FunctionComponent<SpacerProps> = (props) => {
  const { orientation, size } = props;
  if (orientation === 'vertical') return <div style={{width: '5px', height: `${size}px`}}/>
  else if (orientation === 'horizontal') return <div style={{width: `${size}px`, height: '5px'}}/>
  else return <></>
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Flow Gumball Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h2 className={inter.className}>
        Hello
      </h2>
      <Spacer orientation="vertical" size={12}/>
      <Link className={inter.className} href="/login"><b>Go To Login</b></Link>
      </main>
    </>
  )
}
